apiVersion: v1
kind: ConfigMap
metadata:
  name: sb-config
  namespace: simplebank
data:
  ACCESS_TOKEN_DURATION: 60m

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: simplebank
spec:
  replicas: 1
  selector:
    matchLabels: { app: postgres }
  template:
    metadata:
      labels: { app: postgres }
    spec:
      containers:
        - name: simplebank-postgres
          image: postgres:17.6-alpine3.22
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: db-secret, key: POSTGRES_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: db-secret, key: POSTGRES_PASSWORD } }
            - name: POSTGRES_DB
              valueFrom: { secretKeyRef: { name: db-secret, key: POSTGRES_DB } }
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            tcpSocket: { port: 5432 }
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: pgdata
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: simplebank
spec:
  selector: { app: postgres }
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplebank
  namespace: simplebank
spec:
  replicas: 1
  selector:
    matchLabels: { app: simplebank }
  template:
    metadata:
      labels: { app: simplebank }
    spec:
      containers:
        - name: simplebank-api
          image: simplebank:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef: { name: sb-config }
            - secretRef: { name: db-secret }
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: simplebank
  namespace: simplebank
spec:
  selector: { app: simplebank }
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
