name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.21-alpine3.21
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      # Load .env file (non-sensitive vars, dev vars)
      - name: Load .env
        uses: crazy-max/ghaction-dotenv@v3
        with:
          path: .env

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'

      # Install golang-migrate
      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.19.0/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/
          which migrate
          
      # Run migrations
      - name: Run migrations
        run: migrate -path ./internal/db/migration -database "${POSTGRES_URL}" -verbose up

      # Run tests
      - name: Run tests
        run: go test -v -cover ./...
